name: Deploy - Autonsi Stock Adjustment Dongjin - DEV

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository name
        id: get_repo_name
        run: echo "::set-output name=repo_name::$(basename "$(pwd)")"

      - name: Check if module exists
        id: check_module_exists
        uses: appleboy/ssh-action@master
        with:
          host: 3.38.99.151
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_AUTONSI_STOCK_ADJUSTMENT_BASE_DONGJIN }}
          port: 22
          script: |
            if [ -d "/odoo/custom/dongjin_addons/${{ steps.get_repo_name.outputs.repo_name }}" ]; then
              echo "::set-output name=module_exists::true"
            else
              echo "::set-output name=module_exists::false"
            fi

      - name: Conditional Backup
        if: steps.check_module_exists.outputs.module_exists == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: 3.38.99.151
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_AUTONSI_STOCK_ADJUSTMENT_BASE_DONGJIN }}
          port: 22
          script: |
            sudo mkdir -p /odoo/custom/addons_backup && sudo cp -rf /odoo/custom/dongjin_addons/${{ steps.get_repo_name.outputs.repo_name }} /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }}

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: 3.38.99.151
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_AUTONSI_STOCK_ADJUSTMENT_BASE_DONGJIN }}
          port: 22
          source: "."
          target: "/odoo/custom/dongjin_addons/${{ steps.get_repo_name.outputs.repo_name }}"

      - name: Restart - Update Odoo
        uses: appleboy/ssh-action@master
        with:
          host: 3.38.99.151
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_AUTONSI_STOCK_ADJUSTMENT_BASE_DONGJIN }}
          port: 22
          script: |
            sudo service odoo-server restart
            sudo su odoo -c 'python3 /odoo/odoo-server/odoo-bin -u ${{ steps.get_repo_name.outputs.repo_name }} -d dongjin_1004 --addons-path=/odoo/odoo-server/addons,/odoo/custom/dongjin_addons --dev all --stop-after-init'

      - name: Check upgrade status
        if: ${{ failure() }}
        uses: appleboy/ssh-action@master
        with:
          host: 3.38.99.151
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_AUTONSI_STOCK_ADJUSTMENT_BASE_DONGJIN }}
          port: 22
          script: |
            sudo cp -rf /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }} /odoo/custom/dongjin_addons
            sudo rm -r /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }}
            sudo service odoo-server restart
            sudo su odoo -c 'python3 /odoo/odoo-server/odoo-bin -u ${{ steps.get_repo_name.outputs.repo_name }} -d dongjin_1004 --addons-path=/odoo/odoo-server/addons,/odoo/custom/dongjin_addons --dev all --stop-after-init'

      - name: Setup git config
        run: |
          git config user.name 'token-generator-app[bot]'
          git config user.email '82042599+token-generator-app[bot]@users.noreply.github.com'
      - name: Auto merge
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto ${{ github.event.number }} --merge
